Creating Numpy Arrays

In [4]:
## np.array
import numpy as np

a = np.array([1, 2, 3])

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [6]:
## 2d and 3d

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [9]:
## dtype

np.array([1, 2, 3], dtype= float)

array([1., 2., 3.])

In [10]:
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

In [11]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
## np.arange

np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [15]:
## with reshape

np.arange(1, 11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
## np.ones and np.zeros

np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
## np.random

np.random.random((3, 4))

array([[0.53042641, 0.01828087, 0.21882959, 0.4495084 ],
       [0.39844785, 0.62903432, 0.26238099, 0.20291729],
       [0.95066551, 0.20420543, 0.47510457, 0.91417828]])

In [20]:
## np.linspace

np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
## np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

print(a1)
print('\n')
print(a2)
print('\n')
print(a3)

[0 1 2 3 4 5 6 7 8 9]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [5]:
## ndim - it tells no. of dimensions

a1.ndim

1

In [6]:
a2.ndim

2

In [7]:
a3.ndim

3

In [8]:
## shape - how much item in every dimensions

a1.shape

(10,)

In [9]:
a2.shape

(3, 4)

In [10]:
a3.shape

(2, 2, 2)

In [13]:
## size - no. of items

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [14]:
## itemsize - memory occupation size

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [ ]:
## dtype it tells data type

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


Changing Datatype

In [19]:
## astype

a3.astype('int32')

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Array Opeartions

In [20]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

print(a1)
print('\n')
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
## Scaler operations

## Arithemetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [22]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [23]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [26]:
## Relational operators
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
## Vector opeartions = 2 numpy array operations

## Arithmetic operations

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [30]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

Array Functions

In [31]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)

a1

array([[ 7., 46., 57.],
       [35., 90., 30.],
       [ 2., 79., 17.]])

In [32]:
## max/min/sum/prod

np.max(a1)

90.0

In [33]:
np.min(a1)

2.0

In [34]:
np.sum(a1)

363.0

In [35]:
np.prod(a1)

4658740758000.0

In [36]:
## 0 -> col and 1 -> row

np.max(a1, axis=1)

array([57., 90., 79.])

In [37]:
np.max(a1, axis=0)

array([35., 90., 57.])

In [38]:
np.sum(a1, axis=1)

array([110., 155.,  98.])

In [39]:
## mean/median/std/var

np.mean(a1)

40.333333333333336

In [40]:
np.mean(a1, axis=1)

array([36.66666667, 51.66666667, 32.66666667])

In [42]:
np.median(a1)

35.0

In [43]:
np.std(a1)

28.929031938329512

In [44]:
np.var(a1)

836.8888888888889

In [45]:
## Trignometric functions

np.sin(a1)

array([[ 0.6569866 ,  0.90178835,  0.43616476],
       [-0.42818267,  0.89399666, -0.98803162],
       [ 0.90929743, -0.44411267, -0.96139749]])

In [48]:
## Dot product

a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [49]:
## log and exponents

np.log(a1)

array([[1.94591015, 3.8286414 , 4.04305127],
       [3.55534806, 4.49980967, 3.40119738],
       [0.69314718, 4.36944785, 2.83321334]])

In [50]:
np.exp(a1)

array([[1.09663316e+03, 9.49611942e+19, 5.68572000e+24],
       [1.58601345e+15, 1.22040329e+39, 1.06864746e+13],
       [7.38905610e+00, 2.03828107e+34, 2.41549528e+07]])

In [53]:
## round/floor/ceil

np.round(np.random.random((2, 3))*100)

array([[97., 60., 41.],
       [ 2., 32., 46.]])

In [54]:
np.floor(np.random.random((2, 3))*100)

array([[86., 70., 23.],
       [56., 45., 64.]])

In [55]:
np.ceil(np.random.random((2, 3))*100)

array([[81., 16., 29.],
       [31.,  1., 90.]])

Indexing and Slicing

In [3]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

print(a1)
print()
print(a2)
print()
print(a3)


[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## indexing
a1[-1]

9

In [6]:
a1[0]

0

In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a2[1][2]

a2[1, 2]

6

In [11]:
a2[2, 3]

11

In [12]:
a2[1, 0]

4

In [13]:
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
a3[1, 0, 1]

5

In [15]:
a3[0, 1, 0]

2

In [16]:
a3[0, 0, 0]

0

In [17]:
a3[1, 1, 0]

6

In [18]:
## Slicing - multiple item fetch

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a1[2 : 5]

array([2, 3, 4])

In [20]:
a1[2 : 5 : 2]

array([2, 4])

In [21]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a2[0, :]

array([0, 1, 2, 3])

In [23]:
a2[:, 2]

array([ 2,  6, 10])

In [24]:
a2[1:, 1 : 3]

array([[ 5,  6],
       [ 9, 10]])

In [25]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
a2[1, ::3]

array([4, 7])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [56]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [59]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a3[0, 1,:]
a3[0, 1]

array([3, 4, 5])

In [65]:
a3[1, :,1]

array([10, 13, 16])

In [66]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3

In [70]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [2]:
import numpy as np

a1 = np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1

In [5]:
a2 = np.arange(12).reshape(3, 4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [10]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [11]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [14]:
## 1) reshape
## 2) transpose
## 3) ravel

print(a2)
print()
np.transpose(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [15]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
## ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [19]:
## Horizontal stacking

a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)

print(a4)
print()
print(a5)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [21]:
np.hstack((a4, a5, a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [23]:
## Vertical Stacking

np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spliting

In [24]:
## Horizontal Spiliting

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [26]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [27]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]