np.sort

Return a sorted copy of an array

In [2]:
import numpy as np

a = np.random.randint(1, 100, 15)
a


array([87, 44, 60, 33, 27, 71, 14, 67, 81, 76, 67, 65, 11,  4, 87])

In [3]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[93,  2, 32, 75],
       [93, 68, 32, 22],
       [ 5, 40, 81, 41],
       [57, 38, 31, 57],
       [32, 21, 38, 22],
       [32, 89, 13, 74]])

In [4]:
np.sort(a)

array([ 4, 11, 14, 27, 33, 44, 60, 65, 67, 67, 71, 76, 81, 87, 87])

In [5]:
np.sort(b)

array([[ 2, 32, 75, 93],
       [22, 32, 68, 93],
       [ 5, 40, 41, 81],
       [31, 38, 57, 57],
       [21, 22, 32, 38],
       [13, 32, 74, 89]])

In [6]:
np.sort(b, axis=0)

array([[ 5,  2, 13, 22],
       [32, 21, 31, 22],
       [32, 38, 32, 41],
       [57, 40, 32, 57],
       [93, 68, 38, 74],
       [93, 89, 81, 75]])

In [7]:
np.sort(a)[::-1]

array([87, 87, 81, 76, 71, 67, 67, 65, 60, 44, 33, 27, 14, 11,  4])

np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [9]:
np.append(a, 200)

array([ 87,  44,  60,  33,  27,  71,  14,  67,  81,  76,  67,  65,  11,
         4,  87, 200])

In [10]:
b

array([[93,  2, 32, 75],
       [93, 68, 32, 22],
       [ 5, 40, 81, 41],
       [57, 38, 31, 57],
       [32, 21, 38, 22],
       [32, 89, 13, 74]])

In [11]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)  

array([[93.,  2., 32., 75.,  1.],
       [93., 68., 32., 22.,  1.],
       [ 5., 40., 81., 41.,  1.],
       [57., 38., 31., 57.,  1.],
       [32., 21., 38., 22.,  1.],
       [32., 89., 13., 74.,  1.]])

np.concatenate

numpy.concatenate() functions concatenate a sequence of arrays along an existing axis

In [12]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)


print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

with the help of np.unique() method, we can get the unique values from an array as parameter in np.unique() method

In [15]:
e = np.array([1, 1, 2 , 2, 3 , 4])

In [16]:
np.unique(e)

array([1, 2, 3, 4])

np.expand_dims

with the help of numpy.expand_dims() method, we can get the expanded dimensions of an array

In [20]:
a.shape

(15,)

In [21]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [23]:
np.expand_dims(a, axis=1)

array([[87],
       [44],
       [60],
       [33],
       [27],
       [71],
       [14],
       [67],
       [81],
       [76],
       [67],
       [65],
       [11],
       [ 4],
       [87]])

np.where

The np.where() function returns the indices of elements in an input array where the given condition is satisfied

In [24]:
a

array([87, 44, 60, 33, 27, 71, 14, 67, 81, 76, 67, 65, 11,  4, 87])

In [25]:
## Find all indices where values are greater than 50

np.where(a > 50)

(array([ 0,  2,  5,  7,  8,  9, 10, 11, 14], dtype=int64),)

In [26]:
## replace all values greater than 50 with 0

np.where(a > 50, 0, a)

array([ 0, 44,  0, 33, 27,  0, 14,  0,  0,  0,  0,  0, 11,  4,  0])

In [27]:
np.where(a % 2 == 0, 0, a)

array([87,  0,  0, 33, 27, 71,  0, 67, 81,  0, 67, 65, 11,  0, 87])

np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis .

In [28]:
a

array([87, 44, 60, 33, 27, 71, 14, 67, 81, 76, 67, 65, 11,  4, 87])

In [29]:
np.argmax(a)

0

In [30]:
b

array([[93,  2, 32, 75],
       [93, 68, 32, 22],
       [ 5, 40, 81, 41],
       [57, 38, 31, 57],
       [32, 21, 38, 22],
       [32, 89, 13, 74]])

In [31]:
np.argmax(b, axis=0)

array([0, 5, 2, 0], dtype=int64)

In [32]:
np.argmax(b, axis=1)

array([0, 0, 2, 0, 2, 1], dtype=int64)

In [33]:
np.argmin(a)

13

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis

In [34]:
a

array([87, 44, 60, 33, 27, 71, 14, 67, 81, 76, 67, 65, 11,  4, 87])

In [35]:
np.cumsum(a)

array([ 87, 131, 191, 224, 251, 322, 336, 403, 484, 560, 627, 692, 703,
       707, 794])

In [36]:
b

array([[93,  2, 32, 75],
       [93, 68, 32, 22],
       [ 5, 40, 81, 41],
       [57, 38, 31, 57],
       [32, 21, 38, 22],
       [32, 89, 13, 74]])

In [37]:
np.cumsum(b)

array([  93,   95,  127,  202,  295,  363,  395,  417,  422,  462,  543,
        584,  641,  679,  710,  767,  799,  820,  858,  880,  912, 1001,
       1014, 1088])

In [38]:
np.cumsum(b, axis=0)

array([[ 93,   2,  32,  75],
       [186,  70,  64,  97],
       [191, 110, 145, 138],
       [248, 148, 176, 195],
       [280, 169, 214, 217],
       [312, 258, 227, 291]])

In [39]:
np.cumsum(b, axis=1)

array([[ 93,  95, 127, 202],
       [ 93, 161, 193, 215],
       [  5,  45, 126, 167],
       [ 57,  95, 126, 183],
       [ 32,  53,  91, 113],
       [ 32, 121, 134, 208]])

In [40]:
## np.cumprod

np.cumprod(a)

array([         87,        3828,      229680,     7579440,   204644880,
        1644884592,  1553547808,  1008488032,    83151968,  2024582272,
       -1791941248,  -512064128, -1337738112, -1055985152, -1676395008])

np.perecentile

numpy.percentile function used to compute the nth percentile of the given data(array elements) along the specified axis

In [5]:
import numpy as np

a = np.random.randint(1, 100, 15)
a

array([66, 39, 85, 54, 43, 64, 58, 27, 22, 33,  3, 65, 69, 81, 59])

In [6]:
np.percentile(a, 100)

85.0

In [7]:
np.percentile(a, 0)

3.0

In [8]:
np.percentile(a, 50)

58.0

In [9]:
np.median(a)

58.0

np.histogram 

Numpy has built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form

In [10]:
a 

array([66, 39, 85, 54, 43, 64, 58, 27, 22, 33,  3, 65, 69, 81, 59])

In [11]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([1, 0, 2, 2, 1, 3, 4, 0, 2, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [12]:
np.histogram(a, bins=[0, 50, 100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

np.corrcoef

Return Pearson product - moment correlation coefficients.

In [13]:
salary = np.array([20000, 40000, 250000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[ 1.        , -0.16522107],
       [-0.16522107,  1.        ]])

np.isin

with the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elemnts with different sizes

In [14]:
a

array([66, 39, 85, 54, 43, 64, 58, 27, 22, 33,  3, 65, 69, 81, 59])

In [16]:
np.isin(a, [10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [18]:
a[np.isin(a, [66, 85, 90])]


array([66, 85])

np.flip 

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array

In [19]:
a

array([66, 39, 85, 54, 43, 64, 58, 27, 22, 33,  3, 65, 69, 81, 59])

In [20]:
np.flip(a)

array([59, 81, 69, 65,  3, 33, 22, 27, 58, 64, 43, 54, 85, 39, 66])

In [22]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[91, 31, 94,  8],
       [ 9, 35, 52, 90],
       [99, 48, 76, 21],
       [92, 91, 39, 34],
       [77, 81, 37, 18],
       [97, 53, 78, 14]])

In [23]:
np.flip(b)

array([[14, 78, 53, 97],
       [18, 37, 81, 77],
       [34, 39, 91, 92],
       [21, 76, 48, 99],
       [90, 52, 35,  9],
       [ 8, 94, 31, 91]])

In [24]:
np.flip(b, axis=0)

array([[97, 53, 78, 14],
       [77, 81, 37, 18],
       [92, 91, 39, 34],
       [99, 48, 76, 21],
       [ 9, 35, 52, 90],
       [91, 31, 94,  8]])

np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [27]:
a

array([999, 888,  85,  54,  43,  64,  58,  27,  22,  33,   3,  65,  69,
        81,  59])

In [26]:
np.put(a, [0, 1], [999, 888])

np.delete 

The numpy.delete() function returns a new array with the deletion of sub-arrays along the mentioned axis

In [28]:
a

array([999, 888,  85,  54,  43,  64,  58,  27,  22,  33,   3,  65,  69,
        81,  59])

In [29]:
np.delete(a, 0)

array([888,  85,  54,  43,  64,  58,  27,  22,  33,   3,  65,  69,  81,
        59])

In [30]:
np.delete(a, [0, 1])

array([85, 54, 43, 64, 58, 27, 22, 33,  3, 65, 69, 81, 59])

Set Functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [31]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([4, 5, 6, 7, 8])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.intersect1d(m, n)

array([4, 5])

In [33]:
np.setdiff1d(m, n)

array([1, 2, 3])

In [34]:
np.setxor1d(m, n)

array([1, 2, 3, 6, 7, 8])

In [38]:
m[np.in1d(m, 1)]

array([1])

np.clip 

numpy.clip() function is used to Clip(limit) the values in an array

In [39]:
a

array([999, 888,  85,  54,  43,  64,  58,  27,  22,  33,   3,  65,  69,
        81,  59])

In [41]:
np.clip(a, a_min=10, a_max=50)

array([50, 50, 50, 50, 43, 50, 50, 27, 22, 33, 10, 50, 50, 50, 50])